services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
