// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('register with taken email should show msg', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('register with taken email should show msg', async function() {
    await driver.get("http://localhost:4200/zarejestruj")
    await driver.manage().window().setRect({ width: 989, height: 666 })
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("ala@ala.pl")
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("123456")
    await driver.findElement(By.css(".btn")).click()
    await driver.sleep(3000)
    vars["msg"] = await driver.findElement(By.css("p")).getText()
    assert(vars["msg"].toString() == "Konto z tym emailem już istnieje!")
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:4200/zarejestruj")
  })
})
